# Generated by Django 2.0.13 on 2019-04-13 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xl_name', models.CharField(default='', max_length=50, verbose_name='EXCEL 名称')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('xl_file', models.FileField(upload_to='%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv'])], verbose_name='EXCEL 文件')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(default=' ', max_length=200, verbose_name='英语')),
                ('cn', models.CharField(default=' ', max_length=200, verbose_name='中文')),
                ('comment', models.TextField(default='', max_length=255, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('recite_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='背诵日期')),
                ('recite_count', models.IntegerField(default=1, verbose_name='背诵次数')),
                ('cn2en', models.SmallIntegerField(choices=[(1, 'CN2EN'), (2, 'EN2CN'), (0, 'ALL ALLOW')], default=0, verbose_name='中翻英')),
                ('sentence_or_word', models.SmallIntegerField(choices=[(1, 'Word'), (2, 'Sentence')], default=1, verbose_name='单词还是句子')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='happy_recite_word.ExcelStatus', verbose_name='所属EXCEL文件')),
            ],
        ),
    ]
