# Generated by Django 2.0.13 on 2019-04-15 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_recite_word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelstatus',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
