# Generated by Django 2.0.13 on 2019-04-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_recite_word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='sentence_or_word',
        ),
        migrations.AddField(
            model_name='words',
            name='word_or_sentence',
            field=models.SmallIntegerField(choices=[(1, 'Word'), (2, 'Sentence')], default=1, help_text='WorS(word_or_sentence) : 1(默认) 代表单词; 2 代表句子', verbose_name='单词还是句子'),
        ),
        migrations.AlterField(
            model_name='words',
            name='cn',
            field=models.CharField(default=' ', help_text='cn : 请在此输入中文', max_length=200, verbose_name='中文'),
        ),
        migrations.AlterField(
            model_name='words',
            name='cn2en',
            field=models.SmallIntegerField(choices=[(1, 'CN2EN'), (2, 'EN2CN'), (0, 'ALL ALLOW')], default=0, help_text='cn2en : 1 代表中翻英，2代表英翻中，0（默认）代表都可以，系统会取随机数', verbose_name='中翻英'),
        ),
        migrations.AlterField(
            model_name='words',
            name='comment',
            field=models.TextField(default='', help_text='comment : 请在此输入备注', max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='words',
            name='en',
            field=models.CharField(default=' ', help_text='en : 请在此输入英文', max_length=200, verbose_name='英语'),
        ),
    ]
