# Generated by Django 2.0.13 on 2019-04-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_recite_word', '0002_auto_20190413_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelstatus',
            old_name='xl_name',
            new_name='name',
        ),
    ]
