# Generated by Django 2.0.13 on 2019-04-15 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_recite_word', '0003_auto_20190415_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelstatus',
            name='pdf_file',
            field=models.FileField(default='None', upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
