# Generated by Django 2.0.13 on 2019-04-13 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('happy_recite_word', '0003_auto_20190413_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelstatus',
            name='recite_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='背诵日期'),
        ),
    ]
