# Generated by Django 2.0.13 on 2019-04-16 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_recite_word', '0004_auto_20190415_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='enshrine_time',
            field=models.IntegerField(default=0, help_text='收藏一次单词,该数量自增1', verbose_name='收藏次数'),
        ),
        migrations.AlterField(
            model_name='words',
            name='comment',
            field=models.TextField(default=' ', help_text='comment : 请在此输入备注', max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='words',
            name='recite_count',
            field=models.IntegerField(default=0, verbose_name='背诵次数'),
        ),
        migrations.AlterField(
            model_name='words',
            name='recite_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 1, 1, 1), verbose_name='背诵日期'),
        ),
    ]
