# Generated by Django 2.0.13 on 2019-04-16 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_recite_word', '0005_auto_20190416_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelstatus',
            name='ans_file',
            field=models.FileField(default='None', help_text='答案本', upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='excelstatus',
            name='pdf_file',
            field=models.FileField(default='None', help_text='单词本', upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
