# Generated by Django 2.0.13 on 2019-04-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='create_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='无名大侠', max_length=50, verbose_name='昵称'),
        ),
    ]
